In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, f1_score


data = pd.read_csv('iris.csv')
X = data.drop('Species', axis=1)
y = data['Species']

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

naive_bayes_model = GaussianNB()
naive_bayes_model.fit(X_train, y_train)

y_pred = naive_bayes_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average="weighted")
error_rate = 1 - accuracy


print("The accuracy of the model on the dataset is:", accuracy)
print("The F1 score of the model on the dataset is:", f1)
print("The error rate of the model on the dataset is:", error_rate)

conf_matrix = confusion_matrix(y_test, y_pred, labels=[0, 1, 2])
print("Confusion Matrix:\n", conf_matrix)


The accuracy of the model on the dataset is: 0.9666666666666667
The F1 score of the model on the dataset is: 0.9657687991021324
The error rate of the model on the dataset is: 0.033333333333333326
Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
