In [1]:

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, f1_score


data = pd.read_csv('enjoysports.csv')
X = data.drop('Decision', axis=1)
y = data['Decision']


label_encoder = LabelEncoder()
X['Outlook'] = label_encoder.fit_transform(X['Outlook'])
X['Temp.'] = label_encoder.fit_transform(X['Temp.'])
X['Humidity'] = label_encoder.fit_transform(X['Humidity'])
X['Wind'] = label_encoder.fit_transform(X['Wind'])
y = label_encoder.fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


naive_bayes_model = GaussianNB()
naive_bayes_model.fit(X_train, y_train)


y_pred = naive_bayes_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average="weighted")

print("Accuracy:", accuracy)
print("F1 Score:", f1)


conf_matrix = confusion_matrix(y_test, y_pred, labels=[0, 1, 2])
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.3333333333333333
F1 Score: 0.5
Confusion Matrix:
 [[0 0 0]
 [2 1 0]
 [0 0 0]]
